class Language:
    def __init__(self):
        self.downloaded=""
        self.downloading=""
        self.downloadedSuccefully=""
        self.clipboardEmpty=""
        self.entryEmpty=""
        self.videoUnavailable=""
        self.noValidLink=""
        self.notYoutube=""
        self.error=""
        self.audio=""
        self.video=""
        self.download=""
        self.clear=""
        self.paste=""
        self.browse = ""
        self.menuLanguage = ""

    def EN(self):
        self.downloaded = "Download complete !"
        self.downloading = "Downloading..."
        self.downloadedSuccefully = "has been downloaded successfully !"
        self.clipboardEmpty = "The clipboard is empty !"
        self.entryEmpty = "Enter a link !"
        self.videoUnavailable = "Video unavailable"
        self.noValidLink = "The link isn't valid !"
        self.notYoutube = "Please enter a youtube link !"
        self.error = "Error"
        self.audio = "Audio"
        self.video = "Video"
        self.download = "Download"
        self.clear = "Clear"
        self.paste = "Paste"
        self.browse = "Browse"
        self.menuLanguage = "Language"

    def FR(self):
        self.downloaded = "Téléchargement finis"
        self.downloading = "Téléchargement en cours..."
        self.downloadedSuccefully = "a été téléchargé avec succès !"
        self.clipboardEmpty = "Le presse-papier est vide !"
        self.entryEmpty = "Entrez un lien !"
        self.videoUnavailable = "Vidéo indisponible"
        self.noValidLink = "Le lien n'est pas valide !"
        self.notYoutube = "Entrez un lien youtube !"
        self.error = "Erreur"
        self.audio = "Audio"
        self.video = "Vidéo"
        self.download = "Téléchargement"
        self.clear = "Effacer"
        self.paste = "Coller "
        self.browse = "Parcourir"
        self.menuLanguage = "Langue"
